version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - java -version
  build:
    commands:
      - ./mvnw package -Dmaven.test.skip
artifacts:
  files:
    - '*.jar'
  base-directory: $CODEBUILD_SRC_DIR/target

cache:
  paths:
    - '/root/.m2/**/*'
